### PR TITLE
Feature/revsdl 967 module types

### PR DESCRIPTION
**Pull request by bonewell**
**Implemented:**
1. PoliciesManager must add "moduleType" field to policies database when creating this database in case such exists in Preloaded PT
2. PoliciesManager must add "moduleType" field to policies database when updating this database in case Updated PT comes
3. PoliciesManager must add "moduleType" field to SnapshotPT in case such field exists in policies database.
4. "moduleType" field is optional for all SnapshotPT, Updated PT, Preloaded PT (that is, in case "moduleType" is omitted in the table, the table is still valid).
5. "moduleType" field must be supported for only "default" and "<appID>" sub-sections of "app_policies" section.
6. "moduleType" must be an array of string values
7. "moduleType" valid values are only those listed in "ModuleType" enumeration of mobile_API (that is, any other values must be treated as invalid).
8. In case "moduleType" has invalid value and one and more valid values, PoliciesManager must cut this invalid value off and leave valid values as they are.
9. In case "moduleType" has only invalid values in the array, PoliciesManager must ignore the whole "moduleType" field and not write it into database.
10. In case "moduleType" has empty array, PoliciesManager must write it into database with an empty array.

### CODE REVIEW

**Comment by VladSemenyuk** [comment]
ButtonPressRequest missed

**Comment by bonewell** [comment]
Oops! I'll fix it on master after this branch will be merged into master. Is it OK?

**Comment by VladSemenyuk** [comment]
You can fix it in feature branch, and commit will be added in pull request automatically

**Comment by VladSemenyuk** [comment]
Reviewed

**Comment by pvysh9** [comment]
Reviewed

**Pull request merged**
