### PR TITLE
Ivdcm/gpb integration

### PR DESCRIPTION
**Pull request by bonewell**
@DKlimenko 
@VladSemenyuk 
please, try to build on your computer

### CODE REVIEW

**Comment by DKlimenko** [comment]
reviewed

**Comment by bonewell** [comment]
@DKlimenko @VladSemenyuk I added protobuf deploying. Please, look at this.

**Comment by bonewell** [comment]
Branch was updated because of conflicts.

**Comment by bonewell** [comment]
@DKlimenko @VladSemenyuk 
updated

**Pull request closed without merging**
